### PR TITLE
Versions

### PR DESCRIPTION
**Pull request by agarciamontoro**
NCBI taxonomy data has no versioning conventions as far as we know, but we should definitely keep some kind of versioning.

(Dummy) proposal: we can mark this first release, with the current files from NCBI FTP, as v1.0 and bump it whenever we (manually?) see there are important updtes to the taxonomy files.

### CODE REVIEW

**Comment by agarciamontoro** [comment]
> @eparejatobes How should we add the date as metadata? Like a constant value in the code itself? Or with some sbt-magic I do not know about?

Friendly ping

**Comment by eparejatobes** [comment]
See https://github.com/sbt/sbt-buildinfo/blob/7b8675de66e25cdf34d2165b4bcfe1e55afcfd0a/notes/0.5.0.markdown#buildinfooptionbuildtime. Anyway this is not urgent right now.

**Pull request merged**
