### PR TITLE
Merge api.ncbitaxonomy

### LINKED ISSUE #14: Merge with api.ncbitaxonomy
Although almost all code was merged, we missed an open PR by @agarciamontoro here https://github.com/ohnosequences/api.ncbitaxonomy/pull/8, which includes sensible changes related to `Rank` data-structures and parsing

### PR DESCRIPTION
**Pull request by ncordon**
Retrieves forgotten code from `api.ncbitaxonomy` about `Rank` encodings

Closes #14

### CODE REVIEW

**Review by agarciamontoro — APPROVED** [review]
LGTM!

**Comment by agarciamontoro** [comment]
Are we adding here the parsing code from https://github.com/ohnosequences/api.ncbitaxonomy/pull/8 or is it useless with the new forest implementation?

I ask merely because this should not close #14 if we're adding anything else from there, isn't it?

**Comment by ncordon** [comment]
Let me see if we can reuse some more code. I think your implementation of a map of father -> children can be used to create the tree using `unfold`.

**Comment by ncordon** [comment]
I'm merging this as it is, because I was aiming to leave an usable package after the merge, but there are too much problems with integration with new `forests` and `s3` packages and the old `aws-scala-tools`, and aside from that polishing of the code is being trickier than expected. I intend to open a new PR just to solve those issues.

**Pull request merged**
